export enum SCREEN_NAME {
	LOGIN = 'LOGIN',
	REGISTR = 'REGISTR',
	SMS_AUTH = 'SMS_AUTH',
	PROFILE = 'PROFILE',//navigator
	PRODUCT_PAGE = 'PRODUCT_PAGE',
	CART_PAGE = 'CART_PAGE',
	SALE_PAGE = 'SALE_PAGE',
	MAP_PAGE = 'MAP_PAGE',
	PAY = 'PAY', //navigator
	DEMO_MENU = 'DEMO_MENU'
}

export enum SCREEN_NAME_TABS {
	MENU_TAB = 'MENU_TAB',
	HISTORY_TAB = 'HISTORY_TAB',
	PROFILE_TAB = 'PROFILE_TAB',
}

export enum SCREEN_NAME_PAY {
	PAY_INPUT = 'PAY_INPUT',
	PAY_SUCCESS = 'PAY_SUCCESS',
	PAY_PROCESS = 'PAY_PROCESS'
}


